${env:CF_DISPATCH_NAMESPACE} = "dummy"
${env:TURSO_GROUP_DATABASE_TOKEN} = "dummy"
${env:TURSO_ORGANIZATION} = "dummy"
${env:CF_ACCOUNT_ID} = "dummy"
${env:CF_API_TOKEN} = "dummy"
${env:OPENROUTER_API_KEY} = "dummy"
${env:OTEL_EXPORTER_OTLP_ENDPOINT} = "http://localhost:4318"
${env:OTEL_EXPORTER_OTLP_HEADERS} = ""
${env:PUBLIC_SUPABASE_URL} = "https://bekbempccbkuyrvjuygr.supabase.co"
${env:PUBLIC_SUPABASE_ANON_KEY} = "sb_publishable_sbXikEupU9bvVBCsjv03pQ_NEem9va7"
${env:SUPABASE_URL} = "https://bekbempccbkuyrvjuygr.supabase.co"
${env:SUPABASE_SERVER_TOKEN} = "sb_publishable_sbXikEupU9bvVBCsjv03pQ_NEem9va7"
${env:CF_API_TOKEN} = ""
${env:CF_ACCOUNT_ID} = ""
${env:CF_ZONE_ID} = ""
${env:CF_R2_ACCESS_KEY_ID} = ""
${env:CF_R2_SECRET_ACCESS_KEY} = ""
${env:RESEND_API_KEY} = ""
${env:OPENROUTER_API_KEY} = ""
${env:WALLET_API_KEY} = ""
${env:ANTHROPIC_API_KEY} = ""
${env:OPENAI_API_KEY} = ""
${env:DEEPSEEK_API_KEY} = ""
${env:GOOGLE_API_KEY} = ""
${env:STRIPE_SECRET_KEY} = ""
${env:STRIPE_WEBHOOK_SECRET} = ""
${env:CURRENCY_API_KEY} = ""
${env:LLMS_ENCRYPTION_KEY} = ""
${env:DECO_CHAT_API_JWT_PUBLIC_KEY} = ""
${env:DECO_CHAT_API_JWT_PRIVATE_KEY} = ""
Start-Process powershell -ArgumentList 'cd apps/web; npm run dev'
Start-Process powershell -ArgumentList 'cd apps/api; npm run dev'
Start-Process powershell -ArgumentList 'cd seo-ecommerce/view; npm run dev'
Start-Process powershell -ArgumentList 'cd seo-ecommerce/server; wrangler dev --port 4000'
