// Generated types - do not edit manually

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type String = string;
export type String_1 = "user" | "assistant" | "system";
export type String_2 = string;
export type String_3 = string;
/**
 * The name of the attachment, usually the file name
 */
export type String_4 = string;
/**
 * Media type of the attachment
 */
export type String_5 = string;
/**
 * URL of the attachment (hosted file or Data URL)
 */
export type String_6 = string;
/**
 * Additional attachments to be sent along with the message
 */
export type Array_1 = Object_1[];
/**
 * Array of messages for the conversation
 */
export type Array = Object[];
/**
 * Skip transaction creation
 */
export type Boolean = boolean;
/**
 * Model ID to use for generation (defaults to workspace default)
 */
export type String_7 = string;
/**
 * Maximum number of tokens to generate
 */
export type Number = number;
/**
 * Temperature for the generation
 */
export type Number_1 = number;
export type String_8 = string;
export type Array_2 = String_8[];

export interface AI_GENERATEInput {
  messages: Array;
  skipTransaction?: Boolean;
  model?: String_7;
  maxTokens?: Number;
  temperature?: Number_1;
  tools?: Object_2;
}
export interface Object {
  id?: String;
  role: String_1;
  content: String_2;
  createdAt?: String_3;
  experimental_attachments?: Array_1;
}
export interface Object_1 {
  name?: String_4;
  contentType?: String_5;
  url: String_6;
}
/**
 * Tools available for the generation
 */
export interface Object_2 {
  [k: string]: Array_2;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The generated text response
 */
export type String_9 = string;
/**
 * Number of tokens in the prompt
 */
export type Number_2 = number;
/**
 * Number of tokens in the completion
 */
export type Number_3 = number;
/**
 * Total number of tokens used
 */
export type Number_4 = number;
/**
 * Transaction ID
 */
export type String_10 = string;
/**
 * Reason why generation finished
 */
export type String_11 = string;

export interface AI_GENERATEOutput {
  text: String_9;
  usage: Object_3;
  finishReason?: String_11;
}
/**
 * Token usage information
 */
export interface Object_3 {
  promptTokens: Number_2;
  completionTokens: Number_3;
  totalTokens: Number_4;
  transactionId?: String_10;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type String_12 = string;
export type String_13 = "user" | "assistant" | "system";
export type String_14 = string;
export type String_15 = string;
/**
 * The name of the attachment, usually the file name
 */
export type String_16 = string;
/**
 * Media type of the attachment
 */
export type String_17 = string;
/**
 * URL of the attachment (hosted file or Data URL)
 */
export type String_18 = string;
/**
 * Additional attachments to be sent along with the message
 */
export type Array_4 = Object_5[];
/**
 * Array of messages for the conversation
 */
export type Array_3 = Object_4[];
/**
 * Skip transaction creation
 */
export type Boolean_1 = boolean;
/**
 * Model ID to use for generation (defaults to workspace default)
 */
export type String_19 = string;
/**
 * Maximum number of tokens to generate
 */
export type Number_5 = number;
/**
 * Temperature for the generation
 */
export type Number_6 = number;
export type String_20 = string;
export type Array_5 = String_20[];

export interface AI_GENERATE_OBJECTInput {
  messages: Array_3;
  schema: Object_6;
  skipTransaction?: Boolean_1;
  model?: String_19;
  maxTokens?: Number_5;
  temperature?: Number_6;
  tools?: Object_7;
}
export interface Object_4 {
  id?: String_12;
  role: String_13;
  content: String_14;
  createdAt?: String_15;
  experimental_attachments?: Array_4;
}
export interface Object_5 {
  name?: String_16;
  contentType?: String_17;
  url: String_18;
}
/**
 * JSON Schema that defines the structure of the object to generate
 */
export interface Object_6 {
  [k: string]: unknown;
}
/**
 * Tools available for the generation
 */
export interface Object_7 {
  [k: string]: Array_5;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Number of tokens in the prompt
 */
export type Number_7 = number;
/**
 * Number of tokens in the completion
 */
export type Number_8 = number;
/**
 * Total number of tokens used
 */
export type Number_9 = number;
/**
 * Transaction ID
 */
export type String_21 = string;
/**
 * Reason why generation finished
 */
export type String_22 = string;

export interface AI_GENERATE_OBJECTOutput {
  /**
   * The generated object according to the provided schema
   */
  object?: {
    [k: string]: unknown;
  };
  usage: Object_8;
  finishReason?: String_22;
}
/**
 * Token usage information
 */
export interface Object_8 {
  promptTokens: Number_7;
  completionTokens: Number_8;
  totalTokens: Number_9;
  transactionId?: String_21;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface DATABASES_GET_METAInput {}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Number_10 = number;

export interface DATABASES_GET_METAOutput {
  bytes?: Number_10;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The date to recover to
 */
export type String_23 = string;

export interface DATABASES_RECOVERYInput {
  date: String_23;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Boolean_2 = boolean;

export interface DATABASES_RECOVERYOutput {
  success: Boolean_2;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The SQL query to run
 */
export type String_24 = string;
/**
 * The parameters to pass to the SQL query
 */
export type Array_6 = unknown[];

export interface DATABASES_RUN_SQLInput {
  sql: String_24;
  params?: Array_6;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Boolean_3 = boolean;
export type Number_11 = number;
export type Number_12 = number;
export type Number_13 = number;
export type Number_14 = number;
export type Number_15 = number;
export type Boolean_4 = boolean;
export type String_25 = "WNAM" | "ENAM" | "WEUR" | "EEUR" | "APAC" | "OC";
export type Number_16 = number;
export type Number_17 = number;
export type Array_8 = unknown[];
export type Boolean_5 = boolean;
export type Array_7 = Object_9[];

export interface DATABASES_RUN_SQLOutput {
  result: Array_7;
}
export interface Object_9 {
  meta?: Object_10;
  results?: Array_8;
  success?: Boolean_5;
}
export interface Object_10 {
  changed_db?: Boolean_3;
  changes?: Number_11;
  duration?: Number_12;
  last_row_id?: Number_13;
  rows_read?: Number_14;
  rows_written?: Number_15;
  served_by_primary?: Boolean_4;
  served_by_region?: String_25;
  size_after?: Number_16;
  timings?: Object_11;
}
export interface Object_11 {
  sql_duration_ms?: Number_17;
}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface DECO_CHAT_VIEWS_LISTInput {}

/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type String_26 = string;
export type String_27 = string;
export type String_28 = string;
export type String_29 = string;
export type String_30 = string;
export type String_31 = string;
export type String_32 = string;
export type String_33 = string;
export type String_34 = string;
export type Array_10 = String_34[];
export type String_35 = string;
export type String_36 = "none" | "open" | "autoPin";
export type Array_9 = Object_12[];

export interface DECO_CHAT_VIEWS_LISTOutput {
  views: Array_9;
}
export interface Object_12 {
  id?: String_26;
  name?: String_27;
  title: String_28;
  description?: String_29;
  icon: String_30;
  url?: String_31;
  mimeTypePattern?: String_32;
  resourceName?: String_33;
  tools?: Array_10;
  prompt?: String_35;
  installBehavior?: String_36;
}

import { z } from "zod";

export type Mcp<T extends Record<string, (input: any) => Promise<any>>> = {
  [K in keyof T]: ((
    input: Parameters<T[K]>[0],
  ) => Promise<Awaited<ReturnType<T[K]>>>) & {
    asTool: () => Promise<{
      inputSchema: z.ZodType<Parameters<T[K]>[0]>;
      outputSchema?: z.ZodType<Awaited<ReturnType<T[K]>>>;
      description: string;
      id: string;
      execute: (
        input: Parameters<T[K]>[0],
      ) => Promise<Awaited<ReturnType<T[K]>>>;
    }>;
  };
};

export const StateSchema = z.object({
  AI_GATEWAY: z.object({
    value: z.string(),
    __type: z.literal("@deco/ai-gateway").default("@deco/ai-gateway"),
  }),
  DATABASE: z.object({
    value: z.string(),
    __type: z.literal("@deco/database").default("@deco/database"),
  }),
});

export interface Env {
  DECO_CHAT_WORKSPACE: string;
  DECO_CHAT_API_JWT_PUBLIC_KEY: string;
  AI_GATEWAY: Mcp<{
    /**
     * Generate text using AI models directly without agent context (stateless)
     */
    AI_GENERATE: (input: AI_GENERATEInput) => Promise<AI_GENERATEOutput>;
    /**
     * Generate structured objects using AI models with JSON schema validation
     */
    AI_GENERATE_OBJECT: (
      input: AI_GENERATE_OBJECTInput,
    ) => Promise<AI_GENERATE_OBJECTOutput>;
  }>;
  DATABASE: Mcp<{
    /**
     * Run a SQL query against the workspace database
     */
    DATABASES_GET_META: (
      input: DATABASES_GET_METAInput,
    ) => Promise<DATABASES_GET_METAOutput>;
    /**
     * Run a SQL query against the workspace database
     */
    DATABASES_RECOVERY: (
      input: DATABASES_RECOVERYInput,
    ) => Promise<DATABASES_RECOVERYOutput>;
    /**
     * Run a SQL query against the workspace database
     */
    DATABASES_RUN_SQL: (
      input: DATABASES_RUN_SQLInput,
    ) => Promise<DATABASES_RUN_SQLOutput>;
    /**
     * List views exposed by this MCP
     */
    DECO_CHAT_VIEWS_LIST: (
      input: DECO_CHAT_VIEWS_LISTInput,
    ) => Promise<DECO_CHAT_VIEWS_LISTOutput>;
  }>;
}

export const Scopes = {
  AI_GATEWAY: {
    AI_GENERATE: "AI_GATEWAY::AI_GENERATE",
    AI_GENERATE_OBJECT: "AI_GATEWAY::AI_GENERATE_OBJECT",
  },
  DATABASE: {
    DATABASES_GET_META: "DATABASE::DATABASES_GET_META",
    DATABASES_RECOVERY: "DATABASE::DATABASES_RECOVERY",
    DATABASES_RUN_SQL: "DATABASE::DATABASES_RUN_SQL",
    DECO_CHAT_VIEWS_LIST: "DATABASE::DECO_CHAT_VIEWS_LIST",
  },
};
