#:schema node_modules/@deco/workers-runtime/config-schema.json
name = "object-storage"
main = "server/main.ts"
compatibility_date = "2025-06-17"
compatibility_flags = [ "nodejs_compat" ]
scope = "deco-team"

[assets]
directory = "./dist/client"
binding = "ASSETS"
not_found_handling = "single-page-application"
run_worker_first = true

[deco]
workspace = "deco-team"
enable_workflows = false
local = false
