/**
 * Theme presets for the deco CMS theme editor
 *
 * Source: https://github.com/jnsahaj/tweakcn (Apache-2.0)
 * Copyright (c) jnsahaj and contributors
 * Licensed under the Apache License, Version 2.0
 *
 * Modifications: Adapted for deco CMS theme system with additional color variants
 */

import type { Theme } from "@deco/sdk";
import { DEFAULT_THEME } from "@deco/sdk";

export interface ThemePreset {
  id: string;
  name: string;
  theme: Theme;
}

// Theme presets - make immutable for tree-shaking
export const THEME_PRESETS = [
  {
    id: "default",
    name: "Deco",
    theme: DEFAULT_THEME,
  },
  {
    id: "modern-minimal",
    name: "Modern Minimal",
    theme: {
      font: {
        type: "Google Fonts",
        name: "Inter",
      },
      variables: {
        "--background": "#ffffff",
        "--foreground": "#333333",
        "--card": "#ffffff",
        "--card-foreground": "#333333",
        "--popover": "#ffffff",
        "--popover-foreground": "#333333",
        "--primary": "#3b82f6",
        "--primary-foreground": "#ffffff",
        "--secondary": "#f3f4f6",
        "--secondary-foreground": "#4b5563",
        "--muted": "#f9fafb",
        "--muted-foreground": "#6b7280",
        "--accent": "#e0f2fe",
        "--accent-foreground": "#1e3a8a",
        "--destructive": "#ef4444",
        "--destructive-foreground": "#ffffff",
        "--success": "#10b981",
        "--success-foreground": "#065f46",
        "--warning": "#f59e0b",
        "--warning-foreground": "#92400e",
        "--border": "#e5e7eb",
        "--input": "#e5e7eb",
        "--ring": "#3b82f6",
        "--chart-1": "#3b82f6",
        "--chart-2": "#60a5fa",
        "--chart-3": "#93c5fd",
        "--chart-4": "#bfdbfe",
        "--chart-5": "#dbeafe",
        "--sidebar": "#f9fafb",
        "--sidebar-foreground": "#333333",
        "--sidebar-accent": "#e0f2fe",
        "--sidebar-accent-foreground": "#1e3a8a",
        "--sidebar-border": "#e5e7eb",
        "--radius": "0.5rem",
        "--spacing": "0.25rem",
        "--shadow-x": "0",
        "--shadow-y": "1px",
        "--shadow-blur": "3px",
        "--shadow-spread": "0px",
        "--shadow-opacity": "0.1",
      },
    },
  },
  {
    id: "twitter",
    name: "Twitter",
    theme: {
      variables: {
        "--background": "#ffffff",
        "--foreground": "#0f1419",
        "--card": "#f7f8f8",
        "--card-foreground": "#0f1419",
        "--popover": "#ffffff",
        "--popover-foreground": "#0f1419",
        "--primary": "#1e9df1",
        "--primary-foreground": "#ffffff",
        "--secondary": "#0f1419",
        "--secondary-foreground": "#ffffff",
        "--muted": "#E5E5E6",
        "--muted-foreground": "#0f1419",
        "--accent": "#E3ECF6",
        "--accent-foreground": "#1e9df1",
        "--destructive": "#f4212e",
        "--destructive-foreground": "#ffffff",
        "--success": "#00ba7c",
        "--success-foreground": "#005a3b",
        "--warning": "#ffad1f",
        "--warning-foreground": "#7c5500",
        "--border": "#e1eaef",
        "--input": "#f7f9fa",
        "--ring": "#1e9df1",
        "--chart-1": "#1e9df1",
        "--chart-2": "#7856ff",
        "--chart-3": "#ff6c44",
        "--chart-4": "#00ba7c",
        "--chart-5": "#ffad1f",
        "--sidebar": "#f7f8f8",
        "--sidebar-foreground": "#0f1419",
        "--sidebar-accent": "#E3ECF6",
        "--sidebar-accent-foreground": "#1e9df1",
        "--sidebar-border": "#e1e8ed",
        "--radius": "0.75rem",
        "--spacing": "0.25rem",
        "--shadow-x": "0",
        "--shadow-y": "1px",
        "--shadow-blur": "3px",
        "--shadow-spread": "0px",
        "--shadow-opacity": "0.08",
      },
    },
  },
  {
    id: "amethyst-haze",
    name: "Amethyst Haze",
    theme: {
      font: {
        type: "Google Fonts",
        name: "Poppins",
      },
      variables: {
        "--background": "#f8f7fa",
        "--foreground": "#3d3c4f",
        "--card": "#ffffff",
        "--card-foreground": "#3d3c4f",
        "--popover": "#ffffff",
        "--popover-foreground": "#3d3c4f",
        "--primary": "#8a79ab",
        "--primary-foreground": "#f8f7fa",
        "--secondary": "#dfd9ec",
        "--secondary-foreground": "#3d3c4f",
        "--muted": "#dcd9e3",
        "--muted-foreground": "#6b6880",
        "--accent": "#e6a5b8",
        "--accent-foreground": "#4b2e36",
        "--destructive": "#d95c5c",
        "--destructive-foreground": "#f8f7fa",
        "--success": "#77b8a1",
        "--success-foreground": "#2a5c49",
        "--warning": "#e6b877",
        "--warning-foreground": "#7c5a2e",
        "--border": "#cec9d9",
        "--input": "#eae7f0",
        "--ring": "#8a79ab",
        "--chart-1": "#8a79ab",
        "--chart-2": "#e6a5b8",
        "--chart-3": "#77b8a1",
        "--chart-4": "#a890c4",
        "--chart-5": "#f0c3d1",
        "--sidebar": "#f1eff5",
        "--sidebar-foreground": "#3d3c4f",
        "--sidebar-accent": "#e6a5b8",
        "--sidebar-accent-foreground": "#4b2e36",
        "--sidebar-border": "#d7d2e0",
        "--radius": "0.75rem",
        "--spacing": "0.25rem",
        "--shadow-x": "0",
        "--shadow-y": "2px",
        "--shadow-blur": "4px",
        "--shadow-spread": "0px",
        "--shadow-opacity": "0.12",
      },
    },
  },
  {
    id: "catppuccin",
    name: "Catppuccin",
    theme: {
      variables: {
        "--background": "#eff1f5",
        "--foreground": "#4c4f69",
        "--card": "#ffffff",
        "--card-foreground": "#4c4f69",
        "--popover": "#ccd0da",
        "--popover-foreground": "#4c4f69",
        "--primary": "#8839ef",
        "--primary-foreground": "#ffffff",
        "--secondary": "#ccd0da",
        "--secondary-foreground": "#4c4f69",
        "--muted": "#dce0e8",
        "--muted-foreground": "#6c6f85",
        "--accent": "#04a5e5",
        "--accent-foreground": "#ffffff",
        "--destructive": "#d20f39",
        "--destructive-foreground": "#ffffff",
        "--success": "#40a02b",
        "--success-foreground": "#1a4d11",
        "--warning": "#df8e1d",
        "--warning-foreground": "#6f450a",
        "--border": "#bcc0cc",
        "--input": "#ccd0da",
        "--ring": "#8839ef",
        "--chart-1": "#8839ef",
        "--chart-2": "#04a5e5",
        "--chart-3": "#40a02b",
        "--chart-4": "#df8e1d",
        "--chart-5": "#d20f39",
        "--sidebar": "#e6e9ef",
        "--sidebar-foreground": "#4c4f69",
        "--sidebar-accent": "#04a5e5",
        "--sidebar-accent-foreground": "#ffffff",
        "--sidebar-border": "#bcc0cc",
        "--radius": "0.5rem",
        "--spacing": "0.25rem",
        "--shadow-x": "0",
        "--shadow-y": "1px",
        "--shadow-blur": "3px",
        "--shadow-spread": "0px",
        "--shadow-opacity": "0.1",
      },
    },
  },
  {
    id: "kodama-grove",
    name: "Kodama Grove",
    theme: {
      variables: {
        "--background": "#fbfff3",
        "--foreground": "#1a1a1a",
        "--card": "#f9fcf2",
        "--card-foreground": "#1a1a1a",
        "--popover": "#f9fcf2",
        "--popover-foreground": "#1a1a1a",
        "--primary": "#84cc16",
        "--primary-foreground": "#ffffff",
        "--secondary": "#e5f3c0",
        "--secondary-foreground": "#1a1a1a",
        "--muted": "#f2f7df",
        "--muted-foreground": "#5a6c3f",
        "--accent": "#e5f3c0",
        "--accent-foreground": "#1a1a1a",
        "--destructive": "#ef4444",
        "--destructive-foreground": "#ffffff",
        "--success": "#84cc16",
        "--success-foreground": "#365314",
        "--warning": "#f59e0b",
        "--warning-foreground": "#78350f",
        "--border": "#d9e8a3",
        "--input": "#e5f3c0",
        "--ring": "#84cc16",
        "--chart-1": "#84cc16",
        "--chart-2": "#a3e635",
        "--chart-3": "#bef264",
        "--chart-4": "#65a30d",
        "--chart-5": "#4d7c0f",
        "--sidebar": "#f5fae6",
        "--sidebar-foreground": "#1a1a1a",
        "--sidebar-accent": "#e5f3c0",
        "--sidebar-accent-foreground": "#1a1a1a",
        "--sidebar-border": "#d9e8a3",
        "--radius": "0.5rem",
        "--spacing": "0.25rem",
        "--shadow-x": "0",
        "--shadow-y": "1px",
        "--shadow-blur": "3px",
        "--shadow-spread": "0px",
        "--shadow-opacity": "0.1",
      },
    },
  },
  {
    id: "quantum-rose",
    name: "Quantum Rose",
    theme: {
      variables: {
        "--background": "#fff0f3",
        "--foreground": "#1f1315",
        "--card": "#fff5f7",
        "--card-foreground": "#1f1315",
        "--popover": "#fff5f7",
        "--popover-foreground": "#1f1315",
        "--primary": "#e11d48",
        "--primary-foreground": "#ffffff",
        "--secondary": "#ffd6e0",
        "--secondary-foreground": "#1f1315",
        "--muted": "#ffe0e8",
        "--muted-foreground": "#6b4c52",
        "--accent": "#ffd6e0",
        "--accent-foreground": "#1f1315",
        "--destructive": "#dc2626",
        "--destructive-foreground": "#ffffff",
        "--success": "#059669",
        "--success-foreground": "#064e3b",
        "--warning": "#d97706",
        "--warning-foreground": "#78350f",
        "--border": "#ffc1d4",
        "--input": "#ffd6e0",
        "--ring": "#e11d48",
        "--chart-1": "#e11d48",
        "--chart-2": "#be123c",
        "--chart-3": "#9f1239",
        "--chart-4": "#fb7185",
        "--chart-5": "#fda4af",
        "--sidebar": "#fff8fa",
        "--sidebar-foreground": "#1f1315",
        "--sidebar-accent": "#ffd6e0",
        "--sidebar-accent-foreground": "#1f1315",
        "--sidebar-border": "#ffc1d4",
        "--radius": "0.5rem",
        "--spacing": "0.25rem",
        "--shadow-x": "0",
        "--shadow-y": "1px",
        "--shadow-blur": "3px",
        "--shadow-spread": "0px",
        "--shadow-opacity": "0.1",
      },
    },
  },
  {
    id: "elegant-luxury",
    name: "Elegant Luxury",
    theme: {
      font: {
        type: "Google Fonts",
        name: "Playfair Display",
      },
      variables: {
        "--background": "#1c1917",
        "--foreground": "#f5f5f4",
        "--card": "#292524",
        "--card-foreground": "#f5f5f4",
        "--popover": "#292524",
        "--popover-foreground": "#f5f5f4",
        "--primary": "#d4af37",
        "--primary-foreground": "#1c1917",
        "--secondary": "#44403c",
        "--secondary-foreground": "#e7e5e4",
        "--muted": "#292524",
        "--muted-foreground": "#a8a29e",
        "--accent": "#44403c",
        "--accent-foreground": "#e7e5e4",
        "--destructive": "#dc2626",
        "--destructive-foreground": "#ffffff",
        "--success": "#22c55e",
        "--success-foreground": "#ffffff",
        "--warning": "#eab308",
        "--warning-foreground": "#ffffff",
        "--border": "#44403c",
        "--input": "#44403c",
        "--ring": "#d4af37",
        "--chart-1": "#d4af37",
        "--chart-2": "#c99a2e",
        "--chart-3": "#b8860b",
        "--chart-4": "#fbbf24",
        "--chart-5": "#92400e",
        "--sidebar": "#1c1917",
        "--sidebar-foreground": "#f5f5f4",
        "--sidebar-accent": "#44403c",
        "--sidebar-accent-foreground": "#e7e5e4",
        "--sidebar-border": "#44403c",
        "--radius": "0.375rem",
        "--spacing": "0.25rem",
        "--shadow-x": "0",
        "--shadow-y": "2px",
        "--shadow-blur": "4px",
        "--shadow-spread": "0px",
        "--shadow-opacity": "0.3",
      },
    },
  },
  {
    id: "mocha-mousse",
    name: "Mocha Mousse",
    theme: {
      variables: {
        "--background": "#F1F0E5",
        "--foreground": "#56453F",
        "--card": "#F1F0E5",
        "--card-foreground": "#56453F",
        "--popover": "#FFFFFF",
        "--popover-foreground": "#56453F",
        "--primary": "#A37764",
        "--primary-foreground": "#FFFFFF",
        "--secondary": "#BAAB92",
        "--secondary-foreground": "#ffffff",
        "--muted": "#E4C7B8",
        "--muted-foreground": "#8A655A",
        "--accent": "#E4C7B8",
        "--accent-foreground": "#56453F",
        "--destructive": "#1f1a17",
        "--destructive-foreground": "#FFFFFF",
        "--success": "#6d9447",
        "--success-foreground": "#2d3d1d",
        "--warning": "#d9a84f",
        "--warning-foreground": "#6c5420",
        "--border": "#BAAB92",
        "--input": "#BAAB92",
        "--ring": "#A37764",
        "--chart-1": "#A37764",
        "--chart-2": "#8A655A",
        "--chart-3": "#C39E88",
        "--chart-4": "#D4B5A1",
        "--chart-5": "#9C7B6A",
        "--sidebar": "#ebd6cb",
        "--sidebar-foreground": "#56453F",
        "--sidebar-accent": "#C39E88",
        "--sidebar-accent-foreground": "#ffffff",
        "--sidebar-border": "#A28777",
        "--radius": "0.5rem",
        "--spacing": "0.25rem",
        "--shadow-x": "0",
        "--shadow-y": "2px",
        "--shadow-blur": "4px",
        "--shadow-spread": "0px",
        "--shadow-opacity": "0.1",
      },
    },
  },
  {
    id: "notebook",
    name: "Notebook",
    theme: {
      font: {
        type: "Google Fonts",
        name: "Merriweather",
      },
      variables: {
        "--background": "#f9f9f9",
        "--foreground": "#3a3a3a",
        "--card": "#ffffff",
        "--card-foreground": "#3a3a3a",
        "--popover": "#ffffff",
        "--popover-foreground": "#3a3a3a",
        "--primary": "#606060",
        "--primary-foreground": "#f0f0f0",
        "--secondary": "#dedede",
        "--secondary-foreground": "#3a3a3a",
        "--muted": "#e3e3e3",
        "--muted-foreground": "#505050",
        "--accent": "#f3eac8",
        "--accent-foreground": "#5d4037",
        "--destructive": "#c87a7a",
        "--destructive-foreground": "#ffffff",
        "--success": "#82a674",
        "--success-foreground": "#3a5230",
        "--warning": "#d4a373",
        "--warning-foreground": "#6a5139",
        "--border": "#747272",
        "--input": "#ffffff",
        "--ring": "#606060",
        "--chart-1": "#606060",
        "--chart-2": "#909090",
        "--chart-3": "#c0c0c0",
        "--chart-4": "#f3eac8",
        "--chart-5": "#d4a373",
        "--sidebar": "#f0f0f0",
        "--sidebar-foreground": "#3a3a3a",
        "--sidebar-accent": "#f3eac8",
        "--sidebar-accent-foreground": "#5d4037",
        "--sidebar-border": "#c0c0c0",
        "--radius": "0",
        "--spacing": "0.25rem",
        "--shadow-x": "1px",
        "--shadow-y": "1px",
        "--shadow-blur": "2px",
        "--shadow-spread": "0px",
        "--shadow-opacity": "0.15",
      },
    },
  },
  {
    id: "graphite",
    name: "Graphite",
    theme: {
      variables: {
        "--background": "#f0f0f0",
        "--foreground": "#333333",
        "--card": "#f5f5f5",
        "--card-foreground": "#333333",
        "--popover": "#f5f5f5",
        "--popover-foreground": "#333333",
        "--primary": "#606060",
        "--primary-foreground": "#ffffff",
        "--secondary": "#e0e0e0",
        "--secondary-foreground": "#333333",
        "--muted": "#d9d9d9",
        "--muted-foreground": "#666666",
        "--accent": "#c0c0c0",
        "--accent-foreground": "#333333",
        "--destructive": "#cc3333",
        "--destructive-foreground": "#ffffff",
        "--success": "#5b8c5a",
        "--success-foreground": "#2d462d",
        "--warning": "#d97706",
        "--warning-foreground": "#78350f",
        "--border": "#d0d0d0",
        "--input": "#e0e0e0",
        "--ring": "#606060",
        "--chart-1": "#606060",
        "--chart-2": "#757575",
        "--chart-3": "#9e9e9e",
        "--chart-4": "#bdbdbd",
        "--chart-5": "#e0e0e0",
        "--sidebar": "#eaeaea",
        "--sidebar-foreground": "#333333",
        "--sidebar-accent": "#c0c0c0",
        "--sidebar-accent-foreground": "#333333",
        "--sidebar-border": "#d0d0d0",
        "--radius": "0.375rem",
        "--spacing": "0.25rem",
        "--shadow-x": "0",
        "--shadow-y": "1px",
        "--shadow-blur": "3px",
        "--shadow-spread": "0px",
        "--shadow-opacity": "0.1",
      },
    },
  },
  {
    id: "cosmic-night",
    name: "Cosmic Night",
    theme: {
      variables: {
        "--background": "#0f0a1f",
        "--foreground": "#e0d7f5",
        "--card": "#1a1429",
        "--card-foreground": "#e0d7f5",
        "--popover": "#1a1429",
        "--popover-foreground": "#e0d7f5",
        "--primary": "#a855f7",
        "--primary-foreground": "#ffffff",
        "--secondary": "#312647",
        "--secondary-foreground": "#e0d7f5",
        "--muted": "#1f1833",
        "--muted-foreground": "#9888c7",
        "--accent": "#2d2348",
        "--accent-foreground": "#c084fc",
        "--destructive": "#f43f5e",
        "--destructive-foreground": "#ffffff",
        "--success": "#22c55e",
        "--success-foreground": "#ffffff",
        "--warning": "#f59e0b",
        "--warning-foreground": "#ffffff",
        "--border": "#372a54",
        "--input": "#261c40",
        "--ring": "#a855f7",
        "--chart-1": "#a855f7",
        "--chart-2": "#c084fc",
        "--chart-3": "#e9d5ff",
        "--chart-4": "#8b5cf6",
        "--chart-5": "#6d28d9",
        "--sidebar": "#0d0819",
        "--sidebar-foreground": "#e0d7f5",
        "--sidebar-accent": "#2d2348",
        "--sidebar-accent-foreground": "#c084fc",
        "--sidebar-border": "#372a54",
        "--radius": "0.75rem",
        "--spacing": "0.25rem",
        "--shadow-x": "0",
        "--shadow-y": "2px",
        "--shadow-blur": "8px",
        "--shadow-spread": "0px",
        "--shadow-opacity": "0.4",
      },
    },
  },
  {
    id: "nature",
    name: "Nature",
    theme: {
      variables: {
        "--background": "#f0fdf4",
        "--foreground": "#14532d",
        "--card": "#f7fef9",
        "--card-foreground": "#14532d",
        "--popover": "#f7fef9",
        "--popover-foreground": "#14532d",
        "--primary": "#10b981",
        "--primary-foreground": "#ffffff",
        "--secondary": "#d1fae5",
        "--secondary-foreground": "#14532d",
        "--muted": "#dcfce7",
        "--muted-foreground": "#166534",
        "--accent": "#d1fae5",
        "--accent-foreground": "#14532d",
        "--destructive": "#dc2626",
        "--destructive-foreground": "#ffffff",
        "--success": "#10b981",
        "--success-foreground": "#065f46",
        "--warning": "#f59e0b",
        "--warning-foreground": "#78350f",
        "--border": "#bbf7d0",
        "--input": "#d1fae5",
        "--ring": "#10b981",
        "--chart-1": "#10b981",
        "--chart-2": "#34d399",
        "--chart-3": "#6ee7b7",
        "--chart-4": "#059669",
        "--chart-5": "#047857",
        "--sidebar": "#ecfdf5",
        "--sidebar-foreground": "#14532d",
        "--sidebar-accent": "#d1fae5",
        "--sidebar-accent-foreground": "#14532d",
        "--sidebar-border": "#bbf7d0",
        "--radius": "0.5rem",
        "--spacing": "0.25rem",
        "--shadow-x": "0",
        "--shadow-y": "1px",
        "--shadow-blur": "3px",
        "--shadow-spread": "0px",
        "--shadow-opacity": "0.08",
      },
    },
  },
  {
    id: "amber-minimal",
    name: "Amber Minimal",
    theme: {
      variables: {
        "--background": "#fffbeb",
        "--foreground": "#78350f",
        "--card": "#fffef7",
        "--card-foreground": "#78350f",
        "--popover": "#fffef7",
        "--popover-foreground": "#78350f",
        "--primary": "#f59e0b",
        "--primary-foreground": "#ffffff",
        "--secondary": "#fef3c7",
        "--secondary-foreground": "#78350f",
        "--muted": "#fef9c3",
        "--muted-foreground": "#a16207",
        "--accent": "#fef3c7",
        "--accent-foreground": "#78350f",
        "--destructive": "#dc2626",
        "--destructive-foreground": "#ffffff",
        "--success": "#16a34a",
        "--success-foreground": "#14532d",
        "--warning": "#f59e0b",
        "--warning-foreground": "#78350f",
        "--border": "#fde68a",
        "--input": "#fef3c7",
        "--ring": "#f59e0b",
        "--chart-1": "#f59e0b",
        "--chart-2": "#fbbf24",
        "--chart-3": "#fcd34d",
        "--chart-4": "#d97706",
        "--chart-5": "#b45309",
        "--sidebar": "#fffaeb",
        "--sidebar-foreground": "#78350f",
        "--sidebar-accent": "#fef3c7",
        "--sidebar-accent-foreground": "#78350f",
        "--sidebar-border": "#fde68a",
        "--radius": "0.5rem",
        "--spacing": "0.25rem",
        "--shadow-x": "0",
        "--shadow-y": "1px",
        "--shadow-blur": "3px",
        "--shadow-spread": "0px",
        "--shadow-opacity": "0.1",
      },
    },
  },
  {
    id: "solar-dusk",
    name: "Solar Dusk",
    theme: {
      variables: {
        "--background": "#fff7ed",
        "--foreground": "#7c2d12",
        "--card": "#fffaf5",
        "--card-foreground": "#7c2d12",
        "--popover": "#fffaf5",
        "--popover-foreground": "#7c2d12",
        "--primary": "#ea580c",
        "--primary-foreground": "#ffffff",
        "--secondary": "#ffedd5",
        "--secondary-foreground": "#7c2d12",
        "--muted": "#fed7aa",
        "--muted-foreground": "#9a3412",
        "--accent": "#ffedd5",
        "--accent-foreground": "#7c2d12",
        "--destructive": "#dc2626",
        "--destructive-foreground": "#ffffff",
        "--success": "#16a34a",
        "--success-foreground": "#14532d",
        "--warning": "#ea580c",
        "--warning-foreground": "#7c2d12",
        "--border": "#fdba74",
        "--input": "#ffedd5",
        "--ring": "#ea580c",
        "--chart-1": "#ea580c",
        "--chart-2": "#f97316",
        "--chart-3": "#fb923c",
        "--chart-4": "#c2410c",
        "--chart-5": "#9a3412",
        "--sidebar": "#fff4ed",
        "--sidebar-foreground": "#7c2d12",
        "--sidebar-accent": "#ffedd5",
        "--sidebar-accent-foreground": "#7c2d12",
        "--sidebar-border": "#fdba74",
        "--radius": "0.5rem",
        "--spacing": "0.25rem",
        "--shadow-x": "0",
        "--shadow-y": "2px",
        "--shadow-blur": "4px",
        "--shadow-spread": "0px",
        "--shadow-opacity": "0.12",
      },
    },
  },
  {
    id: "perpetuity",
    name: "Perpetuity",
    theme: {
      variables: {
        "--background": "#ecfeff",
        "--foreground": "#164e63",
        "--card": "#f7feff",
        "--card-foreground": "#164e63",
        "--popover": "#f7feff",
        "--popover-foreground": "#164e63",
        "--primary": "#06b6d4",
        "--primary-foreground": "#ffffff",
        "--secondary": "#cffafe",
        "--secondary-foreground": "#164e63",
        "--muted": "#e0f2fe",
        "--muted-foreground": "#155e75",
        "--accent": "#cffafe",
        "--accent-foreground": "#164e63",
        "--destructive": "#dc2626",
        "--destructive-foreground": "#ffffff",
        "--success": "#14b8a6",
        "--success-foreground": "#134e4a",
        "--warning": "#f59e0b",
        "--warning-foreground": "#78350f",
        "--border": "#a5f3fc",
        "--input": "#cffafe",
        "--ring": "#06b6d4",
        "--chart-1": "#06b6d4",
        "--chart-2": "#0891b2",
        "--chart-3": "#0e7490",
        "--chart-4": "#22d3ee",
        "--chart-5": "#67e8f9",
        "--sidebar": "#f0fdff",
        "--sidebar-foreground": "#164e63",
        "--sidebar-accent": "#cffafe",
        "--sidebar-accent-foreground": "#164e63",
        "--sidebar-border": "#a5f3fc",
        "--radius": "0.5rem",
        "--spacing": "0.25rem",
        "--shadow-x": "0",
        "--shadow-y": "1px",
        "--shadow-blur": "3px",
        "--shadow-spread": "0px",
        "--shadow-opacity": "0.1",
      },
    },
  },
  {
    id: "tangerine",
    name: "Tangerine",
    theme: {
      variables: {
        "--background": "#fff7ed",
        "--foreground": "#7c2d12",
        "--card": "#fffaf5",
        "--card-foreground": "#7c2d12",
        "--popover": "#fffaf5",
        "--popover-foreground": "#7c2d12",
        "--primary": "#f97316",
        "--primary-foreground": "#ffffff",
        "--secondary": "#ffedd5",
        "--secondary-foreground": "#7c2d12",
        "--muted": "#fed7aa",
        "--muted-foreground": "#9a3412",
        "--accent": "#ffedd5",
        "--accent-foreground": "#7c2d12",
        "--destructive": "#dc2626",
        "--destructive-foreground": "#ffffff",
        "--success": "#16a34a",
        "--success-foreground": "#14532d",
        "--warning": "#f97316",
        "--warning-foreground": "#7c2d12",
        "--border": "#fdba74",
        "--input": "#ffedd5",
        "--ring": "#f97316",
        "--chart-1": "#f97316",
        "--chart-2": "#fb923c",
        "--chart-3": "#fdba74",
        "--chart-4": "#ea580c",
        "--chart-5": "#c2410c",
        "--sidebar": "#fff4ed",
        "--sidebar-foreground": "#7c2d12",
        "--sidebar-accent": "#ffedd5",
        "--sidebar-accent-foreground": "#7c2d12",
        "--sidebar-border": "#fdba74",
        "--radius": "0.75rem",
        "--spacing": "0.25rem",
        "--shadow-x": "0",
        "--shadow-y": "1px",
        "--shadow-blur": "3px",
        "--shadow-spread": "0px",
        "--shadow-opacity": "0.1",
      },
    },
  },
  {
    id: "bold-tech",
    name: "Bold Tech",
    theme: {
      variables: {
        "--background": "#0f0a1a",
        "--foreground": "#e9e3ff",
        "--card": "#1a1329",
        "--card-foreground": "#e9e3ff",
        "--popover": "#1a1329",
        "--popover-foreground": "#e9e3ff",
        "--primary": "#7c3aed",
        "--primary-foreground": "#ffffff",
        "--secondary": "#2a1f3d",
        "--secondary-foreground": "#e9e3ff",
        "--muted": "#1f1833",
        "--muted-foreground": "#a995d5",
        "--accent": "#2d2348",
        "--accent-foreground": "#a78bfa",
        "--destructive": "#ef4444",
        "--destructive-foreground": "#ffffff",
        "--success": "#22c55e",
        "--success-foreground": "#ffffff",
        "--warning": "#f59e0b",
        "--warning-foreground": "#ffffff",
        "--border": "#372a54",
        "--input": "#261c40",
        "--ring": "#7c3aed",
        "--chart-1": "#7c3aed",
        "--chart-2": "#8b5cf6",
        "--chart-3": "#a78bfa",
        "--chart-4": "#6d28d9",
        "--chart-5": "#5b21b6",
        "--sidebar": "#0d0819",
        "--sidebar-foreground": "#e9e3ff",
        "--sidebar-accent": "#2d2348",
        "--sidebar-accent-foreground": "#a78bfa",
        "--sidebar-border": "#372a54",
        "--radius": "0.5rem",
        "--spacing": "0.25rem",
        "--shadow-x": "0",
        "--shadow-y": "2px",
        "--shadow-blur": "8px",
        "--shadow-spread": "0px",
        "--shadow-opacity": "0.4",
      },
    },
  },
  {
    id: "supabase",
    name: "Supabase",
    theme: {
      variables: {
        "--background": "#0f1729",
        "--foreground": "#f5f5f5",
        "--card": "#1a2332",
        "--card-foreground": "#f5f5f5",
        "--popover": "#1a2332",
        "--popover-foreground": "#f5f5f5",
        "--primary": "#3ecf8e",
        "--primary-foreground": "#0f1729",
        "--secondary": "#1e293b",
        "--secondary-foreground": "#f5f5f5",
        "--muted": "#1e293b",
        "--muted-foreground": "#94a3b8",
        "--accent": "#1e293b",
        "--accent-foreground": "#3ecf8e",
        "--destructive": "#ef4444",
        "--destructive-foreground": "#ffffff",
        "--success": "#3ecf8e",
        "--success-foreground": "#ffffff",
        "--warning": "#f59e0b",
        "--warning-foreground": "#ffffff",
        "--border": "#334155",
        "--input": "#1e293b",
        "--ring": "#3ecf8e",
        "--chart-1": "#3ecf8e",
        "--chart-2": "#10b981",
        "--chart-3": "#06b6d4",
        "--chart-4": "#22c55e",
        "--chart-5": "#14b8a6",
        "--sidebar": "#0d1321",
        "--sidebar-foreground": "#f5f5f5",
        "--sidebar-accent": "#1e293b",
        "--sidebar-accent-foreground": "#3ecf8e",
        "--sidebar-border": "#334155",
        "--radius": "0.5rem",
        "--spacing": "0.25rem",
        "--shadow-x": "0",
        "--shadow-y": "2px",
        "--shadow-blur": "8px",
        "--shadow-spread": "0px",
        "--shadow-opacity": "0.4",
      },
    },
  },
  {
    id: "claymorphism",
    name: "Claymorphism",
    theme: {
      variables: {
        "--background": "#f3f4f6",
        "--foreground": "#1f2937",
        "--card": "#ffffff",
        "--card-foreground": "#1f2937",
        "--popover": "#ffffff",
        "--popover-foreground": "#1f2937",
        "--primary": "#6366f1",
        "--primary-foreground": "#ffffff",
        "--secondary": "#e5e7eb",
        "--secondary-foreground": "#1f2937",
        "--muted": "#f9fafb",
        "--muted-foreground": "#6b7280",
        "--accent": "#f3e8ff",
        "--accent-foreground": "#6b21a8",
        "--destructive": "#ef4444",
        "--destructive-foreground": "#ffffff",
        "--success": "#10b981",
        "--success-foreground": "#065f46",
        "--warning": "#f59e0b",
        "--warning-foreground": "#92400e",
        "--border": "#d1d5db",
        "--input": "#e5e7eb",
        "--ring": "#6366f1",
        "--chart-1": "#6366f1",
        "--chart-2": "#8b5cf6",
        "--chart-3": "#ec4899",
        "--chart-4": "#4f46e5",
        "--chart-5": "#7c3aed",
        "--sidebar": "#f9fafb",
        "--sidebar-foreground": "#1f2937",
        "--sidebar-accent": "#f3e8ff",
        "--sidebar-accent-foreground": "#6b21a8",
        "--sidebar-border": "#d1d5db",
        "--radius": "0.75rem",
        "--spacing": "0.25rem",
        "--shadow-x": "0",
        "--shadow-y": "4px",
        "--shadow-blur": "12px",
        "--shadow-spread": "0px",
        "--shadow-opacity": "0.15",
      },
    },
  },
  {
    id: "neo-brutalism",
    name: "Neo Brutalism",
    theme: {
      variables: {
        "--background": "#ffffff",
        "--foreground": "#000000",
        "--card": "#ffffff",
        "--card-foreground": "#000000",
        "--popover": "#ffffff",
        "--popover-foreground": "#000000",
        "--primary": "#ff6b6b",
        "--primary-foreground": "#ffffff",
        "--secondary": "#4ecdc4",
        "--secondary-foreground": "#000000",
        "--muted": "#f5f5f5",
        "--muted-foreground": "#666666",
        "--accent": "#ffe66d",
        "--accent-foreground": "#000000",
        "--destructive": "#ff6b6b",
        "--destructive-foreground": "#ffffff",
        "--success": "#4ecdc4",
        "--success-foreground": "#0a4a44",
        "--warning": "#ffe66d",
        "--warning-foreground": "#7a6600",
        "--border": "#000000",
        "--input": "#ffffff",
        "--ring": "#ff6b6b",
        "--chart-1": "#ff6b6b",
        "--chart-2": "#4ecdc4",
        "--chart-3": "#ffe66d",
        "--chart-4": "#ff9a9a",
        "--chart-5": "#7dddd4",
        "--sidebar": "#f5f5f5",
        "--sidebar-foreground": "#000000",
        "--sidebar-accent": "#ffe66d",
        "--sidebar-accent-foreground": "#000000",
        "--sidebar-border": "#000000",
        "--radius": "0rem",
        "--spacing": "0.25rem",
        "--shadow-x": "4px",
        "--shadow-y": "4px",
        "--shadow-blur": "0px",
        "--shadow-spread": "0px",
        "--shadow-opacity": "1",
      },
    },
  },
  {
    id: "cyberpunk",
    name: "Cyberpunk",
    theme: {
      variables: {
        "--background": "#0a0a1a",
        "--foreground": "#e0e0ff",
        "--card": "#151530",
        "--card-foreground": "#e0e0ff",
        "--popover": "#151530",
        "--popover-foreground": "#e0e0ff",
        "--primary": "#ff00ff",
        "--primary-foreground": "#26122b",
        "--secondary": "#00ffff",
        "--secondary-foreground": "#000000",
        "--muted": "#1a1a2e",
        "--muted-foreground": "#a0a0d0",
        "--accent": "#ff0099",
        "--accent-foreground": "#ffffff",
        "--destructive": "#ff3366",
        "--destructive-foreground": "#ffffff",
        "--success": "#00ff88",
        "--success-foreground": "#ffffff",
        "--warning": "#ffcc00",
        "--warning-foreground": "#ffffff",
        "--border": "#3a3a5a",
        "--input": "#1a1a3a",
        "--ring": "#ff00ff",
        "--chart-1": "#ff00ff",
        "--chart-2": "#00ffff",
        "--chart-3": "#ff0099",
        "--chart-4": "#ff00aa",
        "--chart-5": "#00ff88",
        "--sidebar": "#080810",
        "--sidebar-foreground": "#e0e0ff",
        "--sidebar-accent": "#ff0099",
        "--sidebar-accent-foreground": "#ffffff",
        "--sidebar-border": "#3a3a5a",
        "--radius": "0rem",
        "--spacing": "0.25rem",
        "--shadow-x": "0",
        "--shadow-y": "0px",
        "--shadow-blur": "20px",
        "--shadow-spread": "0px",
        "--shadow-opacity": "0.8",
      },
    },
  },
  {
    id: "pastel-dreams",
    name: "Pastel Dreams",
    theme: {
      variables: {
        "--background": "#faf8ff",
        "--foreground": "#4a3f5c",
        "--card": "#ffffff",
        "--card-foreground": "#4a3f5c",
        "--popover": "#ffffff",
        "--popover-foreground": "#4a3f5c",
        "--primary": "#c7b3e5",
        "--primary-foreground": "#ffffff",
        "--secondary": "#e8dff5",
        "--secondary-foreground": "#4a3f5c",
        "--muted": "#f3eeff",
        "--muted-foreground": "#6b5f7e",
        "--accent": "#e5b3d4",
        "--accent-foreground": "#5c3f52",
        "--destructive": "#e57373",
        "--destructive-foreground": "#ffffff",
        "--success": "#a8d5ba",
        "--success-foreground": "#2d5c3f",
        "--warning": "#f5d7a0",
        "--warning-foreground": "#7a5d2e",
        "--border": "#d9c7ed",
        "--input": "#e8dff5",
        "--ring": "#c7b3e5",
        "--chart-1": "#c7b3e5",
        "--chart-2": "#b3d4e5",
        "--chart-3": "#e5b3d4",
        "--chart-4": "#d4c7f0",
        "--chart-5": "#c7e0f0",
        "--sidebar": "#f8f5ff",
        "--sidebar-foreground": "#4a3f5c",
        "--sidebar-accent": "#e5b3d4",
        "--sidebar-accent-foreground": "#5c3f52",
        "--sidebar-border": "#d9c7ed",
        "--radius": "0.75rem",
        "--spacing": "0.25rem",
        "--shadow-x": "0",
        "--shadow-y": "2px",
        "--shadow-blur": "8px",
        "--shadow-spread": "0px",
        "--shadow-opacity": "0.1",
      },
    },
  },
  {
    id: "doom-64",
    name: "Doom 64",
    theme: {
      variables: {
        "--background": "#cccccc",
        "--foreground": "#1f1f1f",
        "--card": "#b0b0b0",
        "--card-foreground": "#1f1f1f",
        "--popover": "#b0b0b0",
        "--popover-foreground": "#1f1f1f",
        "--primary": "#b71c1c",
        "--primary-foreground": "#ffffff",
        "--secondary": "#556b2f",
        "--secondary-foreground": "#ffffff",
        "--muted": "#b8b8b8",
        "--muted-foreground": "#4a4a4a",
        "--accent": "#4682b4",
        "--accent-foreground": "#ffffff",
        "--destructive": "#ff6f00",
        "--destructive-foreground": "#000000",
        "--success": "#556b2f",
        "--success-foreground": "#1f1f1f",
        "--warning": "#ff6f00",
        "--warning-foreground": "#1f1f1f",
        "--border": "#505050",
        "--input": "#505050",
        "--ring": "#b71c1c",
        "--chart-1": "#b71c1c",
        "--chart-2": "#556b2f",
        "--chart-3": "#4682b4",
        "--chart-4": "#d32f2f",
        "--chart-5": "#6a8143",
        "--sidebar": "#b0b0b0",
        "--sidebar-foreground": "#1f1f1f",
        "--sidebar-accent": "#4682b4",
        "--sidebar-accent-foreground": "#ffffff",
        "--sidebar-border": "#505050",
        "--radius": "0",
        "--spacing": "0.25rem",
        "--shadow-x": "2px",
        "--shadow-y": "2px",
        "--shadow-blur": "0px",
        "--shadow-spread": "0px",
        "--shadow-opacity": "0.3",
      },
    },
  },
  {
    id: "violet-bloom",
    name: "Violet Bloom",
    theme: {
      variables: {
        "--background": "#fdfdfd",
        "--foreground": "#000000",
        "--card": "#fdfdfd",
        "--card-foreground": "#000000",
        "--popover": "#fcfcfc",
        "--popover-foreground": "#000000",
        "--primary": "#7033ff",
        "--primary-foreground": "#ffffff",
        "--secondary": "#edf0f4",
        "--secondary-foreground": "#080808",
        "--muted": "#f5f5f5",
        "--muted-foreground": "#525252",
        "--accent": "#e2ebff",
        "--accent-foreground": "#1e69dc",
        "--destructive": "#e54b4f",
        "--destructive-foreground": "#ffffff",
        "--success": "#4ac885",
        "--success-foreground": "#145c34",
        "--warning": "#fd822b",
        "--warning-foreground": "#7c3a0f",
        "--border": "#e7e7ee",
        "--input": "#ebebeb",
        "--ring": "#7033ff",
        "--chart-1": "#7033ff",
        "--chart-2": "#4ac885",
        "--chart-3": "#fd822b",
        "--chart-4": "#5e44ff",
        "--chart-5": "#68d89b",
        "--sidebar": "#f5f8fb",
        "--sidebar-foreground": "#000000",
        "--sidebar-accent": "#ebebeb",
        "--sidebar-accent-foreground": "#000000",
        "--sidebar-border": "#ebebeb",
        "--radius": "0.5rem",
        "--spacing": "0.25rem",
        "--shadow-x": "0",
        "--shadow-y": "1px",
        "--shadow-blur": "3px",
        "--shadow-spread": "0px",
        "--shadow-opacity": "0.08",
      },
    },
  },
  {
    id: "bubblegum",
    name: "Bubblegum",
    theme: {
      variables: {
        "--background": "#f6e6ee",
        "--foreground": "#5b5b5b",
        "--card": "#fdedc9",
        "--card-foreground": "#5b5b5b",
        "--popover": "#ffffff",
        "--popover-foreground": "#5b5b5b",
        "--primary": "#d04f99",
        "--primary-foreground": "#ffffff",
        "--secondary": "#8acfd1",
        "--secondary-foreground": "#333333",
        "--muted": "#b2e1eb",
        "--muted-foreground": "#7a7a7a",
        "--accent": "#fbe2a7",
        "--accent-foreground": "#333333",
        "--destructive": "#f96f70",
        "--destructive-foreground": "#ffffff",
        "--success": "#84d2e2",
        "--success-foreground": "#1a5c5f",
        "--warning": "#fbe2a7",
        "--warning-foreground": "#7a6623",
        "--border": "#d04f99",
        "--input": "#e4e4e4",
        "--ring": "#d04f99",
        "--chart-1": "#d04f99",
        "--chart-2": "#84d2e2",
        "--chart-3": "#fbe2a7",
        "--chart-4": "#e678b8",
        "--chart-5": "#a3dceb",
        "--sidebar": "#f8d8ea",
        "--sidebar-foreground": "#333333",
        "--sidebar-accent": "#f9a8d4",
        "--sidebar-accent-foreground": "#333333",
        "--sidebar-border": "#f3e8ff",
        "--radius": "0.75rem",
        "--spacing": "0.25rem",
        "--shadow-x": "0",
        "--shadow-y": "2px",
        "--shadow-blur": "8px",
        "--shadow-spread": "0px",
        "--shadow-opacity": "0.15",
      },
    },
  },
  {
    id: "clean-slate",
    name: "Clean Slate",
    theme: {
      variables: {
        "--background": "#f8fafc",
        "--foreground": "#0f172a",
        "--card": "#ffffff",
        "--card-foreground": "#0f172a",
        "--popover": "#ffffff",
        "--popover-foreground": "#0f172a",
        "--primary": "#64748b",
        "--primary-foreground": "#ffffff",
        "--secondary": "#f1f5f9",
        "--secondary-foreground": "#0f172a",
        "--muted": "#f1f5f9",
        "--muted-foreground": "#64748b",
        "--accent": "#e2e8f0",
        "--accent-foreground": "#1e293b",
        "--destructive": "#ef4444",
        "--destructive-foreground": "#ffffff",
        "--success": "#10b981",
        "--success-foreground": "#065f46",
        "--warning": "#f59e0b",
        "--warning-foreground": "#92400e",
        "--border": "#e2e8f0",
        "--input": "#f1f5f9",
        "--ring": "#64748b",
        "--chart-1": "#64748b",
        "--chart-2": "#94a3b8",
        "--chart-3": "#cbd5e1",
        "--chart-4": "#475569",
        "--chart-5": "#334155",
        "--sidebar": "#f8fafc",
        "--sidebar-foreground": "#0f172a",
        "--sidebar-accent": "#e2e8f0",
        "--sidebar-accent-foreground": "#1e293b",
        "--sidebar-border": "#e2e8f0",
        "--radius": "0.375rem",
        "--spacing": "0.25rem",
        "--shadow-x": "0",
        "--shadow-y": "1px",
        "--shadow-blur": "2px",
        "--shadow-spread": "0px",
        "--shadow-opacity": "0.05",
      },
    },
  },
  {
    id: "retro-arcade",
    name: "Retro Arcade",
    theme: {
      variables: {
        "--background": "#1a1a2e",
        "--foreground": "#eee",
        "--card": "#16213e",
        "--card-foreground": "#eee",
        "--popover": "#0f3460",
        "--popover-foreground": "#eee",
        "--primary": "#ff6b6b",
        "--primary-foreground": "#ffffff",
        "--secondary": "#4ecdc4",
        "--secondary-foreground": "#1a1a2e",
        "--muted": "#0f3460",
        "--muted-foreground": "#94a1b2",
        "--accent": "#ffe66d",
        "--accent-foreground": "#1a1a2e",
        "--destructive": "#e74c3c",
        "--destructive-foreground": "#ffffff",
        "--success": "#4ecdc4",
        "--success-foreground": "#ffffff",
        "--warning": "#ffe66d",
        "--warning-foreground": "#ffffff",
        "--border": "#334e68",
        "--input": "#0f3460",
        "--ring": "#ff6b6b",
        "--chart-1": "#ff6b6b",
        "--chart-2": "#4ecdc4",
        "--chart-3": "#ffe66d",
        "--chart-4": "#ff9a9a",
        "--chart-5": "#7dddd4",
        "--sidebar": "#16213e",
        "--sidebar-foreground": "#eee",
        "--sidebar-accent": "#ffe66d",
        "--sidebar-accent-foreground": "#1a1a2e",
        "--sidebar-border": "#334e68",
        "--radius": "0.375rem",
        "--spacing": "0.25rem",
        "--shadow-x": "0",
        "--shadow-y": "0px",
        "--shadow-blur": "15px",
        "--shadow-spread": "0px",
        "--shadow-opacity": "0.6",
      },
    },
  },
] as const satisfies ReadonlyArray<ThemePreset>;
